# Generated by Django 5.2.6 on 2025-09-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comunicado_conceptocobro_factura_notificacion_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptocobro',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
