# Generated by Django 5.2.6 on 2025-09-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conceptocobro_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicadounidad',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
