# Generated by Django 5.2.6 on 2025-09-16 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comunicadounidad_leido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariorol',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
